name: Check use statement style

on:
  push:
    paths:
      - 'gds/**'
  pull_request:
    paths:
      - 'gds/**'

jobs:
  nested-uses-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run nested use checker
        run: |
          python3 tools/find_nested_uses.py
